language: go

matrix:
  include:
    - go: "tip"
    - go: "1.x"
    - go: "1.10"
    - go: "1.9"
    - go: "1.8"
  allow_failures:
    - go: tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
